language: scala
scala:
- 2.11.5
jdk:
- oraclejdk8
sudo: false
script:
- sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M clean coverage test
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
- sbt coveralls
notifications:
  slack:
    secure: PKQe6hKY8yWhrDQTp/p4EZpVe8MOn+bo7iRaDbOX70lYtLGikHUsOn93ko1B+TQdhqt48P/ITu6I49QPDLZewqTPPJtpROnC8vLxSlAeinT2KGpdt5qds7G9MpNUuMUeehsLWGO0R6gJ4qW2EwOXx2ww0rMIMFbjxWNbyxsm1Lc=
env:
  global:
  - secure: apW3tCl3baDSTysXUkYjYrl9elhJ88TOoaTkP7E45+/S0/e5kQhmh7hHV2kxqsc8Myxt4/dVHh+iX+wYrTL3fYphUXEooQclkQF/ccz+3hK/SFtHZE9aU7sWGUmgDEmNElsOqi4gEgC8erCX+v4TK+CKEJ7SlQyASJ1wKKx2XbA=
  - secure: OOxrG53EGeuEwUobrt4aP9RMDLw5SRk3hAp0oiTl70tIFKq6kQxrThsM5LhSNeWq7okR3/zEC0NReXjJDieADkwtWfjP1q1flmtOZmWPLlRJXANXZpmudNyRi8sSfcVJ4PwAjkxPaaBsCywYiCxJzdIz2xqsNJ4DVIF4hpEOpb4=
  - secure: J53o6uOMVCHshHNcMiSMYohTBJDEMM3qXstvrpAIr7f6vF+MU+YLinFLRYRUWSSbueve0l/dVcdrTZivV5fN9pAB80IQlPQv2kWIJgOsOQwWmO7CMPvUFvlT883t/56ArSOAVVQcp1Gz/PE7Yjiy5tlhPDlVi3wHPAcdUTzoUMs=
  - secure: T1QQm60CjPsgCdjKYVPHP2W7AcLUtn7oqFSr86ejP9fX5AnpwtkFZqkcgc6NzEeIAwJLqDcBrWPONKX77pTiEQl+DIRsfT8YalBV2kDHx3ruJ9uqfTPi39LsYzN7ZJeGnTs0c0vViq1EtBFco/fgtHB3G/bU+7NDTuphX1mKcqs=

after_success:
  - >
      test "${TRAVIS_PULL_REQUEST}" = 'false' &&
      test "${TRAVIS_JDK_VERSION}" = 'oraclejdk8' &&
#      sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' publish &&
      sh "$TRAVIS_BUILD_DIR/.travis.credentials.sh" &&
      sbt 'set version := version.value + "." + System.getenv("TRAVIS_BUILD_NUMBER")' publish